sudo: required
dist: trusty

language: java
jdk:
- oraclejdk8

cache:
  directories:
  - $HOME/.m2/repository

before_install:
# allocate commits to CI, not the owner of the deploy key
- git config user.name "opentracingci"
- git config user.email "opentracingci+opentracing@googlegroups.com"

# setup https authentication credentials, used by ./mvnw release:prepare
- git config credential.helper "store --file=.git/credentials"
- echo "https://$GH_TOKEN:@github.com" > .git/credentials

install:
# Override default travis to use the maven wrapper
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
- ./travis/publish.sh

branches:
  except:
  - /^[0-9]/

after_success:
- mvn jacoco:report coveralls:report

env:
  global:
  # Ex. travis encrypt BINTRAY_USER=your_github_account
  - secure: "0Bnop6xIBmTtvCdrVUDJMdizUrjSJBD33eZsR/mKXQXMtb/LKNyQoU4zRPl7dQ+qrFAa4vxqo4/xp9ddhB0B0u3niScUUa3mtFHkDW+GA9D3YBjpR7epZb3eUxpEGdLjDzJua1RRmRPz76waLQtsGt8GANKs7NgEnz1tc6ZMWQh7km7C3HwpLW1nvU7qtM8Qp1Teyu0bcjgbjn2QzlVp6O6NKW02eEEtkM1wacQTzwrNwcC5UjfCd5C0TNnlttowTEcAvL/U8lwZGmqOvI3kW3QO2HESnwSk3ii0Mo+XD6kT0DDnPc75yUwd6KujzkvkhcwkWVr7LKZacajIxTkg4ETGmbVRvNkUTeKS4GSYV+Ij4V5vYVeZRUbN2IJkohzyYWBeE0i+zdSzmCtjyYv62S2ZvFmbaLoUv2uDtHWRjQFCTHOoF6nZRkQR+azHHc2/bV6Nk5M7Rc+6Kyxn5uM7Dz0REy6dUjf3VV8GlZ26Xoh/mleRuC2SLyTd00ZghU75lRVPSJclKkpS1hS0yqSOkQDyBx4gp2T3x0sR1kDXEelVQN3LRMf75vmQaOkpfJR9yTT2k1VwrN7FRh/OA/jVe9VbfZ7q1b9XuEqWqLN++BG9mgXZ702dkfpC6NkyWhWftWOfUiFhDenDFvJttOXGUm3pzCFIJhkgvsuFP+2cT5w="
  # Ex. travis encrypt BINTRAY_KEY=xxx-https://bintray.com/profile/edit-xxx --add
  - secure: "SYh39L1ZBzPy9dXtI6pWqH9H3/Q6d5HiQoyHYeHBwZwNsZXaukm2Imz67DW87LvAlt9lBfXyJ+rQKigxO2EoubW/2nkXqVOd40vQNCk1jwho/5XYFJEmwjluxEfDpWwmbt6c2XSqaSnEREtcpZiRykr9KuvQoerD0I4WphAzpfgzTZ1hNoF3PsOcI2VcZ+l2N9RQEa6v9miTfQSAZnq/6C8wgoDjn0guNs1579dKqAkHKmZgoltQChBCJ2XiFhC8B5gH74oD107SncVBt5xELvU//npmk6fP9TDyBMSXmNULBCfHnpSS7jRlc5j/mALxqGzZt8VJfktFp0pkoBK2dYRyl7Sj6N3uv8dRKKz3831GPQLbezrtVF42FjuNWGACeyN/vE6uRClXpXGNFj7MRIgSuksgp8mMdk/KjVo2LJGbwD9+X5WRu6o1KrF+j3xI+8vGgaktjNW66v1kepINkcfY47e+8O9ZTwTSh6A17tWvm2USurIydM0h1jILYP2wry2k7D9LhUcvcoUJWiB/HXOPzfUoBXbqyabkl2ha941HMcfnc2JzKDJ83Qa6ZXv2hdH3Y2tHvqLx3UYkyy9gdJ7uNWOxNksk64dEW3hGpI9NJD4P8vg/2syRuktL3S5ibv6R6USbHNrFFhjDFbP3B/gSucXUfyd8RrvacDNH4EE="
  # Ex. travis encrypt GH_TOKEN=XXX-https://github.com/settings/tokens-XXX --add
  - secure: "FbLzcOuZikriy33f1vDr10U85E63AgZbSTSW8yIVDpg5z50h6C62HjWtTYqt9Z9F8lqbchNU50RTUqCRWZEy3DwVstqs8MFG0AAFfUMwD3CkVxQD8LJnan/eOvPLXpHyGlGExeb85Nz5MccwUCqzd86Bj+S1CskXxbUMs3FuUNA1FH4WJccYunewnEOW/JIZ27uMsHNFIUd/tIaRzZxxJZsNqHGRTH7cB/nOaFt+asbcUNGF0Ml9jZneODPKF5y0afqCJJqUS2s8MNkr4zcDmvuok2sOU7ov3BvY0ouGP86bisrO5UcazEFFAjxY/DZ9THjk7/InM9lnQ35oZXtWDJQsc0/YwoCVpbuJb/SuunH1ave3Z+saC771gFOxK2Mbr6rW8/9JROXpQl3+Aib4HR3b2WEeM4Y+rCy0DSiXyKqqX3MtGCJUu/IiUFzDK5OU1EQQAtunOvXBcR0+RY2n/pP1pfydIqc7v44/8+8LZOU0VnsXWHx/K74u2X4jAs5Migi24Gwqn6aHjb0k6S2lo4RsS30ytHC47vFdT5deaVj3hHZcn9IOFCea3K9kzVVwbGeGr0Txs5sCx++JFKusd1pYoMx25gm256Wo8Sv0gK0p1oF+oDEFqEROUT69BjAomlsNYOQUFqJAI6DxIg/2i9Ahga2MXop3kY/scZ1nYtw="
  # Ex. travis encrypt SONATYPE_USER=your_sonatype_account
  - secure: "E/s5ojudUGelqOKoiuhB+fwrXhPiVdB3LjK/TkYEskx0D+MZUvJj80t8wBGgQJgTOnOdPi9F3Ps8rSMdsWyAgb4NBrwbuGiy9lP2qKnb9LG7xNNIFMfHYJyTXB5iCwlkHZJOHVT/KVWSWwRhfITsqP8cbbCLxPu7o+bXP6S/ArIbwFX1F/vIpfwZYcHu3Nd+KAaRzK3j9CIg5vyBDJeUDxKkobWryqa+enxAoyRxTkd8eXz68mSSTgI8TBl9S7NJPsb/lqPgwGsgI1PaHxbD75iajhJSS9Cuyqx0tXFnI23OrMWadgS7yqD4DIeWj3sUht/WUBxGFhoE6vGOq3F+crcIgkU3V71aLz9DpN1zZu8QuHIURkHQZjzwIlhqBHIf8j6s+olCad+6FEVEnx6uzD2ddTCZ2xOsCxliZG2XMM3/v/JEPYkeSH2h6u7ZzpumZC9fcw/7pVrhFS/D5W2NO6N9fmSrYhPchtBxipKkhUR9dXhe1vMPtN4W6TN9Tfctj0393c2kiS7itj7gH9+D+P/4xEhJtmyyW+O5od/ctMgKWAlTez7iEUEAepu0af0iloLP5xvjMjMAsBO/NY5jGACDMUozw5kpNFXz/pczIr7KspDfLUW4pnwsDbb0XPwvJ2lI+qC6VS69BiRxp7AGztQZG3ooxPXXUggTtrWaIeY="
  # Ex. travis encrypt SONATYPE_PASSWORD=your_sonatype_password
  - secure: "KmwzKBgtoneHHvFHDXFO3y9m0g/q/vW1xvnfajiQ/BD4S42nzz0N70Ee8mEmi6RfZdR7uyRfhg0fkNCRkzu25ixx7dUURx4/2xCie7E1WnKYqAYYPl/QHIRLfH797+tO4ixbctvpQzXk5HXRH4m0an6Bc9x53aw6f6FnOssc0gFkMGrTPX3VtiuYWe0udy9j6ilEGMCUKSoZBCV/a92YydO1+sxVVKbj3uOgCDGsOIl+ZDbumSv/yeQmzGIYeQzfjNqSV67PtT+6S1/A9PNfoK1AYHXZUn5zvBqvztJIiKBFiOwYKn9R1iFwNgG7IbJgXB9/txm/Zfe6JhIY/2X+/SNW/DjEc2TRJ4LeJH8cH7uwsPj+cmf2jA7yqiFhEGN11YFrUlsKvvndk/V3Lc45eR58qa5+mVYoBmP2U4Zn+2YnW/RAsOwxCjRZa5gZ69QJITyvxNZrU9joc8/GgOmJBQXK/ePS9YXsaiGiMCnp8WjyxGgzZ8RHY9D8UV3OE8JRr4e510Il65f3DbCnPMHVXc/1p1InqjXx8DW+tzTAqj4EmVn/u9s291xAfQ3MnrVpxxqnw5L8GZwTjCCD6u+nScADVSM5wCauMPpemUGg5Y12wtqQ9uS0I/AH7m4ef3HZAOIq3N5MI8qV/xdlAbKRPGQStKvJCMp6w3r+vnZj4+E="
